travis:
  secure:
    BINSTAR_TOKEN: ItlNnSeumkyVqu6b5/kCIx0zOZfgE1WA8zVhLWFlj0YQ2cpvL7othZZ0ot1QG6mnzaGxldV6Al2KsHVqGARhjj/B1/nD5+suW1cOdm8CXN1yz+OLHO7ufi4s9jUC9+gH1SoDM434+LrA+lvaIXGC+/RI0rvowV7bu1LyUvxhkBzZuLYhWitmzeqsd5lRb8dURPJImdBMBkL14iZ6IV7/pn1HDH6kejGRB+qdUYlUZ8QbyNmSboSzU/C2wcI5q3JoT7FyNRPUu8kEjtfIcGxMSqKzgwYYS5CB6TgPvpyRWAK5u4fA7AFp54Png+CIf9rE+H0yxjpK1dODW3vkECzV1FwG6jvRO7gzATKpcUgRnXuNPP7NojtfvdlXkX01pUt2X+viEvt3Q561hExphXQxaUdCQB0nC9ZOn/J4Qu372kyK9Cv93qLE1y0oUJUt3WF0cCsyC0Qb26Dz7Q18CldxUG1GDrSa7ajDeBJNju0wENhEOSXhEl5cEqqsW630IWoAh6N+LT13uCXpHiLR0qoIGe1LOvM5cFvYzJD+PRfNUvatM+XuZgGkSgogD0IZO6pghwjb1WealtSvrZJBOoZz5Uqr/0ymbCVkCCRPHLWRmP/QMOByG5R8lCsVnFpN3MInjEhVHdjszZt9N6s3SMoM2LQfwJR5J2kXEsO6FEQsbGo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
